### ISSUE TITLE
Singular / plural translations

### ISSUE THREAD

**Issue by jaytaph** [punarinta/xroom.app-translations#14]
It would be a bit nicer to have some translations both singular and plural

        webinar: {
          peersCount: '%s persons are watching',
          peersCountSingle: 'one person is watching',
        },

another option, maybe a little bit more extenable would be to use something like        

     webinar: {
          peersCount: '{0] nobody is watching | {1} one person is watching | {2,inf} %s persons are watching',
        }

**Comment by punarinta** [comment]
@jaytaph thanks for the suggestion! Plurals are actually already fully supported in the core, just not exposed to plugins.

A copy however has to be marked in the code to fetch translations using grammatical number distinction, and also pass the count to the translation function. Otherwise translator will try to fetch a generic, non-numbered, copy.

Then in the translation file things would look like:
```
webinar: {
  peersCount: {
    one: '%s person is watching',
    many: '%s persons are watching',
  },
},
```

Currently only singular/plural is supported but if a necessity we can of course add more complex forms, e.g. Russian one/few/many.

**Comment by jaytaph** [comment]
Is this something we can add to the translation then? It seems a bit weird (in some languages anyway) to say "1 persons are watching"

**Comment by punarinta** [comment]
@jaytaph absolutely. I'll add a ticket.

**Comment by punarinta** [comment]
@jaytaph the support is there now. Here's a usage example: https://github.com/xroom-app/client-translations/commit/c197b3cb5327a8f6fa836663e60bc6f968949a35
Both the old and the new version are supported, so no rush with updating. :)
